Revert "Create att"
yellowrook1/-img-0 pull request #13
Opened 2022-06-05 06:14 UTC by XQLYM

Reverts yellowrook1/-img-0#11

2022-06-07 05:45 UTC, XQLYM reviewed
as

2022-06-07 05:45 UTC, XQLYM commented on att
> -a
aa.

2022-06-07 05:45 UTC, XQLYM commented on att
> -a
a.

2022-06-07 05:46 UTC, yellowrook1 requested changes
k

2022-06-07 05:56 UTC, yellowrook1 reviewed
as

2022-10-15 06:32 UTC, yellowrook1 approved these changes

2023-01-26 20:36 UTC, closed without merging