Update LICENSE
yellowrook1/-img-0 pull request #14
Opened 2022-06-07 06:15 UTC by XQLYM

2022-06-07 06:16 UTC, XQLYM commented on LICENSE
> +   1. Definitions.
```suggestion
   1. Definitions.a 

- [ ] <img>

```

2022-06-07 06:18 UTC, yellowrook1 requested changes
j

2022-06-18 21:12 UTC, XQLYM reviewed
a

2022-06-18 21:12 UTC, XQLYM commented on LICENSE
> +   1. Definitions.a
```suggestion
   1. Definitions.a 
```
```suggestion
   1. Definitions.a 
```
```suggestion
   1. Definitions.a 
```
```suggestion
   1. Definitions.a 
```

2023-01-26 20:36 UTC, closed without merging